# Generated by Django 5.2.0 on 2025-02-20 00:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields

import shopify_sync.encoders


class Migration(migrations.Migration):
    dependencies = [
        ("shopify_sync", "0011_auto_20240806_1405"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "admin_graphql_api_id",
                    models.CharField(max_length=80),
                ),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("sku", models.CharField(max_length=255, null=True)),
                ("tracked", models.BooleanField(default=False)),
                ("requires_shipping", models.BooleanField(default=False)),
                ("country_code_of_origin", models.CharField(max_length=2, null=True)),
                (
                    "province_code_of_origin",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "harmonized_system_code",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "country_harmonized_system_codes",
                    jsonfield.fields.JSONField(
                        dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                        null=True,
                    ),
                ),
                (
                    "unit_cost_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("unit_cost_currency", models.CharField(max_length=3, null=True)),
                ("locations_count", models.IntegerField(null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopify_sync.session",
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_item",
                        to="shopify_sync.variant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "admin_graphql_api_id",
                    models.CharField(max_length=80),
                ),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("activatable", models.BooleanField(default=False)),
                ("deactivatable", models.BooleanField(default=False)),
                ("deletable", models.BooleanField(default=False)),
                ("fulfills_online_orders", models.BooleanField(default=False)),
                ("has_active_inventory", models.BooleanField(default=False)),
                ("has_unfulfilled_orders", models.BooleanField(default=False)),
                ("ships_inventory", models.BooleanField(default=False)),
                (
                    "address",
                    jsonfield.fields.JSONField(
                        dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                        null=True,
                    ),
                ),
                (
                    "local_pickup_settings",
                    jsonfield.fields.JSONField(
                        dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                        null=True,
                    ),
                ),
                ("last_inventory_sync_at", models.DateTimeField(null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopify_sync.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLevel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "admin_graphql_api_id",
                    models.CharField(max_length=80),
                ),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "quantities",
                    jsonfield.fields.JSONField(
                        dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                        null=True,
                    ),
                ),
                ("can_deactivate", models.BooleanField(default=False)),
                ("deactivation_alert", models.TextField(null=True)),
                (
                    "scheduled_changes",
                    jsonfield.fields.JSONField(
                        dump_kwargs={"cls": shopify_sync.encoders.ShopifyDjangoJSONEncoder},
                        null=True,
                    ),
                ),
                ("sync_pending", models.BooleanField(default=False)),
                ("source_updated_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(null=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_levels",
                        to="shopify_sync.inventoryitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_levels",
                        to="shopify_sync.location",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopify_sync.session",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="inventorylevel",
            constraint=models.UniqueConstraint(
                fields=("inventory_item", "location"),
                name="inventory_level_unique_item_location",
            ),
        ),
    ]
